DECLARE 
  P_DATE DATE;
  P_PARAM VARCHAR2(32767);
  RESULTS_CURSOR SYS_REFCURSOR;

BEGIN 
  P_DATE := TO_DATE('01/01/2020', 'DD/MM/RRRR');
  P_PARAM := NULL;
  RESULTS_CURSOR := NULL;

  XXXX.XXXXX ( P_DATE, P_PARAM, RESULTS_CURSOR );
  COMMIT; 
END; 



DECLARE 
  START_DATE VARCHAR2(32767);
  END_DATE VARCHAR2(32767);
  TARGET_POLICY_NO NUMBER;
  C_REPORT PKG_CLAIMS.rc_claims;

BEGIN 
  START_DATE := '06.02.2020';
  END_DATE := '06.02.2020';
  TARGET_POLICY_NO := 1234 ;
  C_REPORT := NULL;

  XXX.XXX ( START_DATE, END_DATE, TARGET_POLICY_NO, C_REPORT );
  COMMIT; 
END;
