DECLARE 
  P_DATE DATE;
  P_PARAM VARCHAR2(32767);
  RESULTS_CURSOR SYS_REFCURSOR;

BEGIN 
  P_DATE := TO_DATE('01/01/2020', 'DD/MM/RRRR');
  P_PARAM := NULL;
  RESULTS_CURSOR := NULL;

  XXXX.XXXXX ( P_DATE, P_PARAM, RESULTS_CURSOR );
  COMMIT; 
END; 
