DECLARE 
val NUMBER;
BEGIN
FOR I IN (SELECT * FROM SYS.ALL_TABLES WHERE OWNER='WINSURE' AND (TABLE_NAME LIKE 'XX%' OR TABLE_NAME LIKE 'XX%')) LOOP
EXECUTE IMMEDIATE 'SELECT count( * ) FROM ' || i.table_name INTO val;
DBMS_OUTPUT.PUT_LINE(i.table_name || ' ==> ' || val );
END LOOP;
END;
